version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go -b 0.0.0.0
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 4001:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
