name: Go Fiber CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Update go.sum
        run: go mod tidy

      - name: Ensure fiber/v2 module in go.sum
        run: go get github.com/gofiber/fiber/v2@latest

      - name: Build and test Go application
        run: |
          cd cmd
          go mod download
          go build -v
          go test -v ./...
