name: Go Fiber CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build and test Go application
        run: |
          go mod download
          go build -v

      - name: Run linter (optional)
        run: golangci-lint run
